package com.tricon.labs.join.exceptions;

public enum ExceptionType {
	
	DATA_VALIDATION, 
	DATABASE, 
	PHONE_CALL, 
	MSG_SENDING, 
	USER_REGISTRATION, 
	ACTION_VALIDATION, 
	FILE_TRANSFER, 
	APPLICATION_PROPERTY, 
	IMAGE_OPERATIONS, 
	AUTHENTICATION, 
	AUTHORISATION, 
	JSON_CONVERSION, 
	INTERNAL_SERVER, 
	GDRIVE, 
	NOT_FOUND, 
	IO_EXCEPTION
	
}
